name: libcalculator
description: A mathematical expression evaluator for Dart that handles arithmetic operations, parentheses, decimal numbers, and proper operator precedence with precise calculations.
version: 1.2.0
repository: https://github.com/MahanRahmati/libcalculator
topics:
  - calculator
  - mathematics

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.12
